# Generated by Django 4.2 on 2025-10-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
