# Generated by Django 4.2 on 2025-10-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_publisher_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
